# Generated by Django 3.1.3 on 2020-11-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools_stats', '0009_auto_20200928_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstats',
            name='group_field_name',
            field=models.CharField(blank=True, help_text='ex. owner_group, invitation__owner_group', max_length=90, null=True, verbose_name='group field name'),
        ),
    ]
